## ClusterSecretStore — Bootstrap Key Vault
##
## Global (cluster-scoped) secret store that references the bootstrap Azure Key
## Vault provisioned by Terraform. ExternalSecret resources in any namespace can
## reference this ClusterSecretStore to sync secrets from the bootstrap vault.
##
## Platform-level secrets stored in the bootstrap Key Vault:
## - LLM API keys (OpenAI, Anthropic) — used by kagent and HolmesGPT
## - GitHub personal access token — used by Platform API to create repos
## - Argo CD admin password (initial bootstrap)
##
## App-level secrets use Crossplane connection secrets instead — each Crossplane
## Composition writes credentials to a namespace-scoped Secret referenced by
## writeConnectionSecretToRef in the Claim.
##
## Authentication: Workload Identity (OIDC federation). The ESO controller pod's
## ServiceAccount is annotated with azure.workload.identity/client-id, which
## triggers the Azure Workload Identity webhook to inject an OIDC token. ESO
## exchanges this for an Azure access token scoped to the Key Vault.
##
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-bootstrap-kv
  labels:
    app.kubernetes.io/name: clustersecretstore
    app.kubernetes.io/instance: azure-bootstrap-kv
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: argocd
spec:
  provider:
    azurekv:
      ## PLACEHOLDER: Replace with actual vault URI from Terraform output.
      ## To retrieve: terraform output -raw keyvault_uri
      ## Example: https://homelab-bootstrap-kv.vault.azure.net/
      vaultUrl: "https://homelab-bootstrap-kv.vault.azure.net/"

      ## Workload Identity auth — no clientId/tenantId needed here because
      ## they're injected via the ServiceAccount annotation.
      authType: WorkloadIdentity

      ## Reference to the ESO controller ServiceAccount (annotated with the
      ## managed identity client ID in values.yaml).
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
