apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: holmesgpt-secrets
  namespace: holmesgpt
  labels:
    app.kubernetes.io/name: holmesgpt
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-bootstrap-kv
    kind: ClusterSecretStore
  target:
    name: holmesgpt-secrets
    creationPolicy: Owner
  data:
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: anthropic-api-key
