apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  namespace: platform
  annotations:
    # Route traffic through NGINX Ingress Controller
    # No rewrite-target annotation; paths are preserved as-is
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # No TLS yet (task #93)
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Rate limiting (per IP)
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-connections: "10"
  labels:
    app.kubernetes.io/name: platform-ingress
    app.kubernetes.io/part-of: homelab-platform
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Platform API: /api/* → platform-api.platform:80
          # Order matters: /api must be before /* to match first
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: platform-api
                port:
                  number: 80

          # Grafana: /grafana/* → monitoring-grafana.monitoring:80
          # Grafana configured with serve_from_sub_path: true
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: monitoring-grafana
                port:
                  number: 80

          # Portal UI: /* → portal-ui.platform:80
          # Must be last rule (catch-all for root and SPA client-side routes)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portal-ui
                port:
                  number: 80
