## Constraint: allowed-repos
##
## Restricts workload images to the homelab ACR. The ACR login server is set to
## the output of the Terraform acr_login_server output. Update this value to match
## your actual ACR URL after running terraform apply.
##
## This enforces the full CI supply chain: images must be built by CI, pushed to ACR,
## and tagged with a semver ref before they can be deployed.
##
## TODO: Replace <ACR_LOGIN_SERVER> with the actual output from Terraform:
##   terraform output -raw acr_login_server
##   e.g., homelab<random>.azurecr.io
##
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedRepos
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: allowed-repos
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["", "apps", "batch"]
        kinds:
          - Pod
          - Deployment
          - StatefulSet
          - DaemonSet
          - Job
          - CronJob
    namespaces:
      - workloads
  parameters:
    repos:
      ## Replace with actual ACR login server from: terraform output -raw acr_login_server
      - "<ACR_LOGIN_SERVER>/"
