## Constraint: no-privileged-containers
##
## Prevents privileged containers in workload namespaces. Platform tooling
## (Falco, Trivy) that legitimately needs elevated capabilities is deployed in its
## own namespace and explicitly excluded from the match scope.
##
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoPrivilegedContainers
metadata:
  annotations:
  name: no-privileged-containers
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["", "apps", "batch"]
        kinds:
          - Pod
          - Deployment
          - StatefulSet
          - DaemonSet
          - Job
          - CronJob
    namespaces:
      - workloads
