apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kagent-secrets
  namespace: kagent-system
  labels:
    app.kubernetes.io/name: kagent
    app.kubernetes.io/component: secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore
  target:
    name: kagent-anthropic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        apiKey: "{{ .anthropicApiKey }}"
  data:
    - secretKey: anthropicApiKey
      remoteRef:
        key: anthropic-api-key
