---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-bootstrap-kv
    kind: ClusterSecretStore

  target:
    name: grafana-admin-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: "{{ .username }}"
        admin-password: "{{ .password }}"

  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: grafana-admin-username
        metadataPolicy: None
      rewrite:
        - regexp:
            source: "(.*)"
            target: "username"
    - extract:
        conversionStrategy: Default  
        decodingStrategy: None
        key: grafana-admin-password
        metadataPolicy: None
      rewrite:
        - regexp:
            source: "(.*)"
            target: "password"
