apiVersion: v1
kind: Namespace
metadata:
  name: kagent-system
  labels:
    app.kubernetes.io/name: kagent
    app.kubernetes.io/component: ai-operations
    app.kubernetes.io/part-of: homelab-platform
