apiVersion: v1
kind: ServiceAccount
metadata:
  name: holmesgpt
  namespace: holmesgpt
  labels:
    app.kubernetes.io/name: holmesgpt
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: ai-operations
