---
# ExternalSecret for Platform API
# Syncs secrets from bootstrap Azure Key Vault to Kubernetes Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-api-secrets
  namespace: platform
  labels:
    app.kubernetes.io/name: platform-api
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: homelab-platform
spec:
  # Refresh interval for secret synchronization
  refreshInterval: 1h

  # Reference to ClusterSecretStore (deployed at wave 3.5)
  secretStoreRef:
    name: azure-bootstrap-kv
    kind: ClusterSecretStore

  # Target Kubernetes Secret configuration
  target:
    name: platform-api-secrets
    creationPolicy: Owner  # ESO owns the Secret lifecycle
    deletionPolicy: Retain # Keep Secret if ExternalSecret is deleted (safety)
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: platform-api
          app.kubernetes.io/component: secret
          app.kubernetes.io/part-of: homelab-platform

  # Secret mappings from Azure Key Vault
  data:
    # GitHub personal access token for repository operations
    # Key Vault secret name: github-pat
    # Required permissions: repo (full control)
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: github-pat

    # OpenAI API key for AI operations (kagent, HolmesGPT, etc.)
    # Key Vault secret name: openai-api-key
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: openai-api-key

    # Argo CD API token for application management
    # Key Vault secret name: argocd-token
    # Generated via: argocd account generate-token --account platform-api
    - secretKey: ARGOCD_TOKEN
      remoteRef:
        key: argocd-token
