package scaffold

import (
	"context"
	"fmt"
	"log/slog"
	"os/exec"
)

// initAndPushRepo initializes a git repository and pushes it to GitHub
func (h *Handler) initAndPushRepo(ctx context.Context, projectDir, repoURL string, req *ScaffoldRequest) error {
	slog.Info("Initializing git repository", "dir", projectDir)

	// Initialize git repo
	if err := h.runGitCommand(ctx, projectDir, "init"); err != nil {
		return fmt.Errorf("git init failed: %w", err)
	}

	// Configure git user (use platform defaults)
	if err := h.runGitCommand(ctx, projectDir, "config", "user.name", "Platform API"); err != nil {
		return fmt.Errorf("git config user.name failed: %w", err)
	}
	if err := h.runGitCommand(ctx, projectDir, "config", "user.email", "platform-api@homelab.local"); err != nil {
		return fmt.Errorf("git config user.email failed: %w", err)
	}

	// Add all files
	if err := h.runGitCommand(ctx, projectDir, "add", "."); err != nil {
		return fmt.Errorf("git add failed: %w", err)
	}

	// Create initial commit
	commitMsg := fmt.Sprintf("Initial commit from %s scaffold\n\nGenerated by Platform API", req.Template)
	if err := h.runGitCommand(ctx, projectDir, "commit", "-m", commitMsg); err != nil {
		return fmt.Errorf("git commit failed: %w", err)
	}

	// Set up remote with authentication
	authenticatedURL := h.getAuthenticatedGitURL(repoURL)
	if err := h.runGitCommand(ctx, projectDir, "remote", "add", "origin", authenticatedURL); err != nil {
		return fmt.Errorf("git remote add failed: %w", err)
	}

	// Rename branch to main (in case default is master)
	if err := h.runGitCommand(ctx, projectDir, "branch", "-M", "main"); err != nil {
		return fmt.Errorf("git branch -M main failed: %w", err)
	}

	// Push to GitHub
	slog.Info("Pushing to GitHub", "repo", repoURL)
	if err := h.runGitCommand(ctx, projectDir, "push", "-u", "origin", "main"); err != nil {
		return fmt.Errorf("git push failed: %w", err)
	}

	slog.Info("Successfully pushed to GitHub", "repo", repoURL)
	return nil
}

// runGitCommand executes a git command in the specified directory
func (h *Handler) runGitCommand(ctx context.Context, dir string, args ...string) error {
	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Dir = dir

	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("git %v failed: %w\nOutput: %s", args, err, string(output))
	}

	slog.Debug("Git command executed", "args", args, "output", string(output))
	return nil
}

// getAuthenticatedGitURL converts an HTTPS clone URL to include the GitHub token
func (h *Handler) getAuthenticatedGitURL(cloneURL string) string {
	// Convert https://github.com/org/repo.git to https://x-access-token:TOKEN@github.com/org/repo.git
	// This allows git push without prompting for credentials
	return fmt.Sprintf("https://x-access-token:%s@%s",
		h.config.GithubToken,
		cloneURL[8:], // Remove "https://" prefix
	)
}
